In [1]:
import tensorflow as tf

In [2]:
x = tf.constant(0.1, shape = [6,6,1,32])

In [11]:
x.get_shape()[1]
#x.shape

Dimension(6)

In [27]:
with tf.Session() as sess:
    k = sess.run(x)
print(len(k[0][0][0]))
print(len(k[0][0]))
print(len(k[0]))
k[0][0][0]

32
1
6


array([ 0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,
        0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,
        0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1], dtype=float32)

In [18]:
x = tf.constant(0.1, shape = [1])

In [19]:
with tf.Session() as sess:
    l = sess.run(x)

l

array([ 0.1], dtype=float32)

In [51]:
x = tf.Variable(tf.constant(1, shape = [2,3]) )
y = tf.Variable(tf.constant(1, shape = [3,3]))
b = tf.Variable(tf.constant(1, shape = [1]))

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    x = sess.run(x)
    y = sess.run(y)
    b = sess.run(b)
    print('x:\n',x,'\n','\n','y:\n',y,'\nprinted'
         )
          
    z = tf.matmul(x,y)
    #z = tf.matmul(x,y)+b
    z = z + b
    z = sess.run(z)

print('\n','\n',z)

x:
 [[1 1 1]
 [1 1 1]] 
 
 y:
 [[1 1 1]
 [1 1 1]
 [1 1 1]] 
printed

 
 [[4 4 4]
 [4 4 4]]
